import {CommingSoon} from '../components';
import {
  CalendarScreen,
  ChangeLanguage,
  DailyDarshan,
  DailyDarshanDetail,
  DailyProgramDetail,
  DailyQuiz,
  DailyQuizDetail,
  DailyQuotes,
  DailyUpdateDetail,
  DailyUpdates,
  DonationScreen,
  EditProfile,
  ForgotPassword,
  FrontDeskScreen,
  GurukulEvents,
  HomeScreen,
  LiveSatsang,
  LoginOTP,
  LoginScreen,
  LoginSuccess,
  PaymentMethod,
  ProfileScreen,
  ProfileSignup,
  ProfileSignupWithEdit,
  QuizHistory,
  QuizResult,
  RegisterScreen,
  ResetPassword,
  Status,
} from '../screens';
import {RootStackParamList} from '../types';
import {AuthStackNavigator, BottomTabNavigator} from './Routes';

export const NativeStackRoute: {
  name: keyof RootStackParamList;
  component: any;
}[] = [
  {name: 'Auth', component: AuthStackNavigator},
  {name: 'BottomNavBar', component: BottomTabNavigator},
  {name: 'dailyDarshan', component: DailyDarshan},
  {name: 'dailyDarshanDetail', component: DailyDarshanDetail},
  {name: 'dailyUpdates', component: DailyUpdates},
  {name: 'dailyUpdateDetail', component: DailyUpdateDetail},
  {name: 'dailyQuotes', component: DailyQuotes},
  {name: 'calendar', component: CalendarScreen},
  {name: 'liveSatsang', component: LiveSatsang},
  {name: 'changeLanguage', component: ChangeLanguage},
  {name: 'editProfile', component: EditProfile},
  {name: 'status', component: Status},
  {name: 'dailyQuiz', component: DailyQuiz},
  {name: 'dailyQuizDetail', component: DailyQuizDetail},
  {name: 'QuizResult', component: QuizResult},
  {name: 'donation', component: DonationScreen},
  {name: 'program', component: CommingSoon},
  {name: 'programDetail', component: DailyProgramDetail},
  {name: 'ProfileEdit', component: ProfileSignupWithEdit},
  {name: 'PaymentMethod', component: PaymentMethod},
  {name: 'GurukulEvents', component: GurukulEvents},
  {name: 'QuizHistory', component: QuizHistory},
];
