export const AllImages = {
  AppLogo: require('../images/SGVP_Logo.png'),
  GurukulLogo: require('../images/GurukulLogo.png'),
  SplashLogo: require('../images/Splash.png'),
  Bgimage: require('../images/Bgimage.png'),
  WrapBG: require('../images/wrapBG.png'),
  CalendarImage: require('../images/Calendar.png'),
  Darshan: require('../images/Darshan.png'),
  Person: require('../images/Person.png'),
  Quotes: require('../images/Quotes.png'),
  Rectangle: require('../images/Rectangle.png'),
  Rectangle2: require('../images/Rectangle2.jpg'),
  Rectangle3: require('../images/Rectangle3.png'),
  Rectangle28: require('../images/Rectangle28.png'),
  Rectangle29: require('../images/Rectangle29.png'),
  Rectangle30: require('../images/Rectangle30.png'),
  Rectangle31: require('../images/Rectangle31.png'),
  DailyQuote: require('../images/DailyQuote.png'),
};
